server {
    listen PORT_PLACEHOLDER default_server;
    location / {
        proxy_pass http://127.0.0.1:8090;
        proxy_set_header Host localhost:8090;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
    }
}
